services:
  account:
    build:
      context: .
      dockerfile: ./account/app.dockerfile
    depends_on:
      - account_db
    environment:
      DATABASE_URL: postgres://haroonalbar:123456@account_db/haroonalbar?sslmode=disable
    restart: on-failure

  catalog:
    build:
      context: .
      dockerfile: ./catalog/app.dockerfile
    depends_on:
      - catalog_db
      # catalog_db:
      #   condition: service_healthy  # Wait for catalog_db to be healthy
    environment:
      # DATABASE_URL: https://catalog_db:9200
      DATABASE_URL: http://catalog_db:9200
    restart: on-failure

  order:
    build:
      context: .
      dockerfile: ./order/app.dockerfile
    depends_on:
      - order_db
    environment:
      DATABASE_URL: postgres://haroonalbar:123456@order_db/haroonalbar?sslmode=disable
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
    restart: on-failure

  graphql:
    build:
      context: .
      dockerfile: ./graphql/app.dockerfile
    ports:
      - 8000:8080
    depends_on:
      - account
      - catalog
    environment:
      ACCOUNT_SERVICE_URL: account:8080
      CATALOG_SERVICE_URL: catalog:8080
      ORDER_SERVICE_URL: order:8080
    restart: on-failure

  account_db:
    build:
      context: ./account
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: haroonalbar
      POSTGRES_USER: haroonalbar
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4 # image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    platform: linux/amd64
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
      # ES_JAVA_OPTS: -Xms2g -Xmx2g  # Increase memory allocation
      # logger.org.elasticsearch: DEBUG  # Enable debug logging
      # healthcheck:
      #   test: ["CMD", "curl", "-f", "https://localhost:9200"]
      #   interval: 60s
      #   timeout: 30s
      #   retries: 5


  order_db:
    build:
      context: ./order
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: haroonalbar
      POSTGRES_USER: haroonalbar
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
