name: Simple Docker Compose Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run services
        run: |
          docker compose up -d
          sleep 30  # Wait for services to start

      - name: Check if services are running
        run: |
          # Check if the GraphQL service is running
          curl -f http://localhost:8000 || exit 1  # GraphQL service

      - name: Tear down services
        run: docker compose down
